name: GitHub Actions Build and Deploy 
on:
  push:
    branches:
      - pelican
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          ref: pelican
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Publish to github pages
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        USER: acefei
        GITHUB_PAGES_BRANCH: master
      run: |
        git config --local user.email "${USER}@github.com"
        git config --local user.name ${USER}
        make publish
        ghp-import -m "Automated deployment: $(date -u) ${GITHUB_SHA}" -b ${GITHUB_PAGES_BRANCH} ./output
        git push -f -q https://${CI_TOKEN}@github.com/${USER}/${USER}.github.io.git ${GITHUB_PAGES_BRANCH}
